/**
 * Stamp the canonical release version across all config files.
 * Run before build. Resolution order:
 *
 *   1. PRINNY_VERSION env var — the CI flow passes the tag from
 *      `create-release` here so every platform job stamps the SAME
 *      version. The tag doesn't physically exist yet during downstream
 *      builds (the release is still a draft — `gh release edit
 *      --draft=false` is what actually creates the git tag), so
 *      `git describe` returns the PREVIOUS tag, which silently shipped
 *      mismatched-version installers and signatures for months.
 *   2. `git describe --tags --abbrev=0` — for local dev / tag-triggered
 *      CI runs where the tag is already present.
 *   3. src-tauri/tauri.conf.json's existing version — last-resort
 *      fallback when neither is available.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

// This value is stamped into tauri.conf.json, Cargo.toml and two package.json
// files by string splice, and is re-interpolated into shell by the artifact
// renaming steps. It originates in a git tag name, which git itself allows to
// contain quotes, `$(` and backticks. Anything that is not a plain semantic
// version is refused here rather than written into a build configuration.
const VERSION_RE = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/;

function assertVersion(value, source) {
  if (!VERSION_RE.test(value)) {
    throw new Error(
      `[bump-version] refusing version ${JSON.stringify(value)} from ${source}: ` +
        'expected MAJOR.MINOR.PATCH'
    );
  }
  return value;
}

function getVersion() {
  const envVersion = process.env.PRINNY_VERSION;
  if (envVersion && envVersion.trim()) {
    const trimmed = envVersion.trim();
    const value = trimmed.startsWith('v') ? trimmed.slice(1) : trimmed;
    return { value: assertVersion(value, 'PRINNY_VERSION env'), source: 'PRINNY_VERSION env' };
  }
  try {
    const tag = execSync('git describe --tags --abbrev=0', {
      cwd: ROOT,
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe'],
    }).trim();
    const value = tag.startsWith('v') ? tag.slice(1) : tag;
    return { value: assertVersion(value, 'git describe'), source: 'git describe' };
  } catch {
    const conf = JSON.parse(readFileSync(join(ROOT, 'src-tauri', 'tauri.conf.json'), 'utf8'));
    return { value: conf.version, source: 'tauri.conf.json fallback' };
  }
}

function replaceInFile(path, pattern, replacement) {
  let content = readFileSync(path, 'utf8');
  const updated = content.replace(pattern, replacement);
  if (updated !== content) {
    writeFileSync(path, updated, 'utf8');
    console.log(`  ${path} -> ${replacement.match(/[\d.]+/)[0]}`);
  }
}

const { value: version, source } = getVersion();
console.log(`[bump-version] Stamping version ${version} (source: ${source})...`);

// tauri.conf.json
replaceInFile(
  join(ROOT, 'src-tauri', 'tauri.conf.json'),
  /"version"\s*:\s*"[^"]+"/,
  `"version": "${version}"`
);

// Cargo.toml
replaceInFile(
  join(ROOT, 'src-tauri', 'Cargo.toml'),
  /^version\s*=\s*"[^"]+"/m,
  `version = "${version}"`
);

// src-tauri/Cargo.lock — the workspace member's own entry. Cargo.toml alone is
// not enough: a lock that still carries the previous version makes any
// `--locked` / `--frozen` build fail outright, and a normal build silently
// rewrites the lock and leaves CI with a dirty tree. Upstream fixes this by
// shelling out to `cargo update --workspace` (cinny-desktop 0660885); we patch
// the entry directly instead so this stays offline-safe — bump-version runs in
// every platform job, including the Android one, before cargo is warmed up.
replaceInFile(
  join(ROOT, 'src-tauri', 'Cargo.lock'),
  /\[\[package\]\]\nname = "cinny"\nversion = "[^"]+"/,
  `[[package]]\nname = "cinny"\nversion = "${version}"`
);

// Root package.json
replaceInFile(
  join(ROOT, 'package.json'),
  /"version"\s*:\s*"[^"]+"/,
  `"version": "${version}"`
);

// cinny/package.json
replaceInFile(
  join(ROOT, 'cinny', 'package.json'),
  /"version"\s*:\s*"[^"]+"/,
  `"version": "${version}"`
);

// Android tauri.properties — gitignored, normally written by `tauri android
// init`, never regenerated by `tauri android build`. Without it,
// build.gradle.kts falls back to versionName "1.0", which makes
// UpdateChecker.kt think every installed copy is behind and re-download
// the APK on every launch.
const parts = version.split('.').map((p) => parseInt(p, 10) || 0);
const [major = 0, minor = 0, patch = 0] = parts;
const versionCode = major * 10000 + minor * 100 + patch;
const propsPath = join(ROOT, 'src-tauri', 'gen', 'android', 'app', 'tauri.properties');
writeFileSync(
  propsPath,
  `tauri.android.versionCode=${versionCode}\ntauri.android.versionName=${version}\n`,
  'utf8'
);
console.log(`  ${propsPath} -> ${version} (code ${versionCode})`);

console.log(`[bump-version] Done.`);
